# Generated by Django 3.0.2 on 2020-02-11 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pit_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_num', models.IntegerField(verbose_name='Team Number')),
                ('robot_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('robot_frame_length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('robot_frame_width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('robot_drivetrain_type', models.CharField(max_length=100)),
                ('robot_vision_type', models.CharField(max_length=100)),
                ('robot_vision_implement', models.CharField(max_length=100)),
                ('robot_goal', models.CharField(max_length=100)),
                ('robot_autonomous', models.CharField(max_length=100)),
                ('robot_highlow', models.CharField(max_length=100)),
                ('robot_climb', models.CharField(max_length=100)),
                ('robot_control_panel', models.CharField(max_length=100)),
                ('notes', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams.Team')),
            ],
        ),
    ]
